language: node_js
sudo: true
node_js:
  - '5.4.1'

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

cache:
  directories:
     - ./node_modules

install:
  - ./tools/ci/install.sh

script:
  - ./tools/ci/test.sh

after_script:
  - ./tools/ci/clean.sh
