language: node_js
sudo: required
dist: trusty
node_js:
  - '5.4.1'

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - g++
      - google-chrome-stable

install:
  - ./tools/ci/install.sh

script:
  - ./tools/ci/test.sh
